name: mldd23
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - black>=23.1.0
  - bokeh>=3.0.3
  - isort>=5.12.0
  - jupyter>=1.0.0
  - matplotlib>=3.7.0
  - notebook>=6.5.2
  - numpy>=1.24.0
  - pandas>=1.5.0
  - pip>=23.0.1
  - pyg>=2.1.0,<3.0.0
  - pytdc>=0.3.8
  - pytest>=7.2.1
  - python>=3.9.0,<3.10.0
  - pytorch>=1.12.0,<2.0.0
  - pytorch-cuda=11.7
  - pyyaml>=6.0
  - rdkit>=2022.03.5
  - scikit-learn=1.2.1
  - scipy>=1.10.1
  - tqdm>=4.64.1
  - yaml>=0.2.5
  - streamlit>=1.10.0